import React from "react";
import { NavBar } from "./components";
import "./globals.css";

export const metadata = {
  title: "CryptoInsight",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-lato">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
