import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "CryptoInsight",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-lato">
        <nav className="flex justify-between font-semibold text-lg items-center px-8 md:px-32 lg:px-64 h-16 backdrop-blur-sm bg-transparent shadow-md text-white bg-gray-900 fixed w-screen z-30">
          <h1 className="text-md md:text-xl">
            <span className="font-normal">Crypto</span>
            <span className="font-bold">Insight</span>
          </h1>
          <ul className="flex gap-4">
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/">Chart</Link>
            </li>
            <li>
              <Link href="/">Lorem Ipsum</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
